server:
  port: 8081

spring:
  application:
    name: user-service
 

  config:
    import: optional:configserver:http://localhost:8090/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user
    username: root
    password: 123456

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serverUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      instance:
        preferIpAddress: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
